name: appsech
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-246.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_datepicker: ^21.2.3
  http: ^1.1.0
  charts_flutter: ^0.12.0
  flutter_custom_clippers: ^2.1.0
  file_picker: ^4.0.0
  progress_dialog_null_safe: ^2.0.0
  syncfusion_flutter_datagrid: ^21.2.10
  fl_chart: ^0.36.0
  intl: ^0.17.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.9
  excel: ^2.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    # - assets/
    - images/