name: appsech
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-246.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_datepicker: ^21.2.3
  http: ^1.1.0
  charts_flutter: ^0.12.0
  flutter_custom_clippers: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    # - assets/
    - images/